[[redirects]]
  from = "http://nubebridalhouse.com/*"
  to = "https://nubebridalhouse.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.nubebridalhouse.com/*"
  to = "https://nubebridalhouse.com/:splat"
  status = 301
  force = true

[build]
  publish = "."
